Repository kh3rld/ksm-lang, pull requests merged in 2024-09, with the labels that each got.

#35 feat(token): Implement token; Coauthored with @kh3rld
  CODE_OF_CONDUCT.md
  LICENSE
  SECURITY.md
  token/token.go
Labels: good first issue

#38 #3 implement number data structure
  error/err.go
  eval/eval.go
  eval/number.go
  lexer/lexer.go
  parser/ast.go
  parser/parser.go
Labels: enhancement

#44 Update README.md for KSM language
  README.md
Labels: documentation, enhancement

#45 Update README.md
  README.md
Labels: documentation
